version: "3"
services:
  # If vpn enabled by default restart docker service and systemctl-daemon after vpn is disabled
  nextjs-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - .env.local

